# Kimbie Dark+ Helix Theme
# Copyright: "80North"
# Created : 2025-08-02

'attribute' = { fg = 'blue' }
'comment' = { fg = 'grey', modifiers = ['italic'] }
'comment.block' = { fg = 'grey', modifiers = ['italic'] }
'comment.block.documentation' = { fg = 'grey', modifiers = ['italic'] }
'constant' = { fg = 'magenta' }
'constant.numeric' = { fg = 'orange' }
'constructor' = { fg = 'cyan' }
'function' = { fg = 'yellow' }
'function.builtin' = { fg = 'blue' }
'function.method' = { fg = 'white' }
'keyword' = { fg = 'cyan' }
'label' = { fg = 'green' }
'namespace' = { fg = 'white' }
'operator' = { fg = 'blue' }
'punctuation.bracket' = { fg = 'cyan' }
'punctuation.delimiter' = { fg = 'cyan', modifiers = ['bold'] }
'punctuation.special' = {fg = 'cyan'}
'string' = { fg = 'green' }
'tag' = { fg = 'cyan' }
'type' = { fg = 'blue' }
'variable' = { fg = 'red' }
'variable.parameter' = { fg = 'white' }

'markup.bold' = { fg = 'orange', modifiers = ['bold'] }
'markup.italic' = { fg = 'magenta', modifiers = ['italic'] }
'markup.strikethrough' = { modifiers = ['crossed_out'] }
'markup.heading' = { fg = 'cyan' }
'markup.link' = { fg = 'orange' }
'markup.link.url' = { fg = 'magenta' }
'markup.link.text' = { fg = 'orange' }
'markup.link.label' = { fg = 'green' }
'markup.list' = { fg = 'cyan' }
'markup.quote' = { fg = 'green', modifiers = ['italic'] }
'markup.raw.block' = { fg = 'green', bg = 'bg' }
'markup.raw.inline' = { fg = 'green', bg = 'bg' }

'diff.plus' = { fg = 'green' }
'diff.minus' = { fg = 'cyan' }
'diff.delta' = { fg = 'blue' }

'ui.background' = { bg = 'bg' }
'ui.cursor' = { bg = 'orange', fg = 'bg-alt' }
'ui.cursor.match' = { fg = 'cyan', modifiers = ['bold'] }
'ui.cursorline' = { bg = 'bg-alt' }
'ui.linenr' = { fg = 'base4' }
'ui.linenr.selected' = { fg = 'orange', bg = 'bg-alt', modifiers = ['bold'] }
'ui.statusline' = { fg = 'fg', bg = 'base3' }
'ui.statusline.normal' = { bg = 'base3' }
'ui.statusline.insert' = { bg = 'base3' }
'ui.statusline.select' = { bg = 'base3' }
'ui.bufferline' = { fg = 'grey', bg = 'base2' }
'ui.bufferline.active' = { fg = 'white', bg = 'base4' }
'ui.bufferline.background' = { bg = 'bg' }
'ui.popup' = { bg = 'bg-alt' }
'ui.window' = { fg = 'grey' }
'ui.help' = { fg = 'fg', bg = 'base2' }
'ui.text' = { fg = 'fg' }
'ui.text.focus' = { bg = 'bg-alt', fg = 'fg' }
'ui.text.info' = { fg = 'fg' }
'ui.virtual.whitespace' = { fg = 'base2' }
'ui.virtual.ruler' = { bg = 'black' }
'ui.menu' = { fg = 'fg', bg = 'bg-alt' }
'ui.menu.selected' = { bg = 'base3', fg = 'fg' }
'ui.selection' = { bg = 'base2' }

'warning' = { fg = 'orange' }
'error' = { fg = 'cyan', modifiers = ['bold'] }
'info' = { fg = 'blue', modifiers = ['bold'] }
'hint' = { fg = 'blue', modifiers = ['bold'] }

'diagnostic.hint' = { underline = { color = 'cyan', style = "curl" } }
'diagnostic.error' = { underline = { color = 'cyan', style = "curl" } }
'diagnostic.info' = { underline = { color = 'blue', style = "curl" } }
'diagnostic.warning' = { underline = { color = 'yellow', style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

'special' = { fg = 'cyan' }

[palette]
white = '#dfdfdf'
black = '#121117'
red = '#d73556'
green = '#a6bd5a'
blue = '#2a6bac'
yellow = '#fcac51'
magenta = '#de7dbf'
cyan = '#569293'
grey = '#5b5b59'
orange = '#c15a1f'

bg = '#221a0f'
bg-alt = '#131510'
fg = '#d4aa7a'
base2 = '#60482f'
base3 = '#83603c'
base4 = '#a57a4c'
